spring:
  kafka:
    bootstrap-servers:
      - localhost:9092
    producer:
      acks: all
      key-serializer:  org.apache.kafka.common.serialization.StringSerializer
      value-serializer:  org.apache.kafka.common.serialization.StringSerializer
      retries: 0
  data:
    mongodb:
      uri: mongodb://localhost:27017/message